language: node_js
node_js:
 - "13"
script:
 - echo "Installing npm and all necessary packages..."
install:
 - npm install -g firebase-tools
 - cd functions/
 - npm install
 - cd ..
after_success:
 - echo "Starting deploy!"
 - firebase deploy --project wildscript-tech --token $FIREBASE_TOKEN
 - echo "Deploy Successful."
